# Generated by Django 5.2.17 on 2026-08-07 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=150)),
                ('company_logo_class', models.CharField(default='fa-solid fa-briefcase', max_length=100)),
                ('position', models.CharField(max_length=150)),
                ('location', models.CharField(blank=True, default='Remote', max_length=100)),
                ('start_date', models.CharField(help_text='e.g. Jan 2022', max_length=50)),
                ('end_date', models.CharField(blank=True, default='Present', max_length=50)),
                ('is_current', models.BooleanField(default=False)),
                ('description', models.TextField(help_text='Line or bullet points of key responsibilities and achievements')),
                ('technologies', models.CharField(blank=True, help_text='Comma-separated tech tags', max_length=255)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Experiences',
                'ordering': ['order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Alex Morgan', max_length=100)),
                ('tagline', models.CharField(default='Senior Fullstack Engineer & Cloud Architect', max_length=200)),
                ('bio', models.TextField(default='Passionate software engineer with over 5+ years of experience building high-scale web applications, distributed backend services, and sleek modern user interfaces.')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('avatar_url', models.CharField(blank=True, default='https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=600&auto=format&fit=crop', max_length=500)),
                ('cv_file', models.FileField(blank=True, null=True, upload_to='cv/')),
                ('cv_url', models.CharField(blank=True, default='#', max_length=500)),
                ('email', models.EmailField(default='alex.morgan.dev@example.com', max_length=254)),
                ('phone', models.CharField(default='+1 (555) 234-5678', max_length=30)),
                ('location', models.CharField(default='San Francisco, CA', max_length=100)),
                ('github_url', models.URLField(blank=True, default='https://github.com')),
                ('linkedin_url', models.URLField(blank=True, default='https://linkedin.com')),
                ('twitter_url', models.URLField(blank=True, default='https://twitter.com')),
                ('years_of_experience', models.IntegerField(default=5)),
                ('projects_completed', models.IntegerField(default=32)),
                ('satisfied_clients', models.IntegerField(default=18)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profile',
            },
        ),
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Project Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Skill Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('short_description', models.CharField(max_length=300)),
                ('full_description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('image_url', models.CharField(blank=True, max_length=500)),
                ('live_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('featured', models.BooleanField(default=True)),
                ('tech_stack', models.CharField(help_text='Comma-separated tech badges, e.g., Python, Django, PostgreSQL', max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='core.projectcategory')),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon_class', models.CharField(blank=True, help_text='FontAwesome icon class e.g. fa-brands fa-python', max_length=100)),
                ('icon_url', models.CharField(blank=True, help_text='SVG icon URL or logo image link', max_length=500)),
                ('proficiency', models.IntegerField(default=85, help_text='Skill percentage (1-100)')),
                ('is_featured', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='core.skillcategory')),
            ],
            options={
                'ordering': ['category', 'order', 'name'],
            },
        ),
    ]
