# Generated by Django 5.1 on 2024-09-01 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('education', models.CharField(max_length=400)),
                ('description', models.TextField()),
                ('CV', models.FileField(upload_to='cv')),
                ('image', models.ImageField(upload_to='profile')),
            ],
        ),
    ]
