# Generated by Django 5.1 on 2024-09-02 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='skill')),
            ],
        ),
    ]
