# Generated by Django 5.1 on 2024-09-02 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_experience_company_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('start', models.DateField(blank=True, null=True)),
                ('end', models.DateField(blank=True, null=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='projects')),
                ('github', models.CharField(blank=True, max_length=500, null=True)),
                ('live', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
