# Generated by Django 5.1 on 2024-09-02 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='category',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
