# Generated by Django 5.1 on 2024-11-19 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_projects_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='skillimage',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
