# Generated by Django 5.1 on 2024-11-19 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_about_status_contact_status_experience_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='status',
        ),
    ]
