# Generated by Django 5.1 on 2026-03-29 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_contact_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='footer')),
                ('url', models.URLField(default='#')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower = first)')),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.DeleteModel(
            name='Footer',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['-start_date']},
        ),
        migrations.AlterModelOptions(
            name='projects',
            options={'ordering': ['order'], 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterModelOptions(
            name='skillimage',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='about',
            name='role',
            field=models.CharField(default='Full Stack Developer', help_text='e.g. Full Stack Developer, Backend Engineer', max_length=200),
        ),
        migrations.AddField(
            model_name='contact',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display order (lower = first)'),
        ),
        migrations.AddField(
            model_name='skillimage',
            name='category',
            field=models.CharField(choices=[('language', 'Languages'), ('framework', 'Frameworks'), ('tool', 'Tools & Platforms'), ('database', 'Databases'), ('devops', 'Cloud & DevOps'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='skillimage',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display order (lower = first)'),
        ),
    ]
