# Generated by Django 5.1 on 2026-03-29 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_sociallink_delete_footer_delete_skill_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='category',
            field=models.CharField(choices=[('e-commerce', 'E-commerce'), ('social-media', 'Social Media'), ('portfolio', 'Portfolio'), ('blog', 'Blog'), ('saas', 'SaaS'), ('api', 'API / Backend'), ('mobile', 'Mobile App'), ('ai-ml', 'AI / ML'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
