# Generated by Django 5.1 on 2026-03-29 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_projects_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='category',
            field=models.CharField(choices=[('shopping', 'Shopping'), ('social', 'Social'), ('portfolio', 'Portfolio'), ('blog', 'Blog'), ('saas', 'SaaS'), ('finance', 'Finance'), ('tools', 'Tools'), ('ai-ml', 'AI / ML'), ('travel', 'Travel'), ('kids', 'Kids'), ('entertainment', 'Entertainment'), ('health', 'Health'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='footer'),
        ),
    ]
