# Generated by Django 5.1 on 2026-03-29 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_projects_category_alter_sociallink_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='category',
            field=models.CharField(choices=[('portfolio', 'Portfolio'), ('blog', 'Blog'), ('saas', 'SaaS'), ('ai-ml', 'AI / ML'), ('art-design', 'Art & Design'), ('business', 'Business'), ('communication', 'Communication'), ('dating', 'Dating'), ('education', 'Education'), ('entertainment', 'Entertainment'), ('finance', 'Finance'), ('food-drink', 'Food & Drink'), ('games', 'Games'), ('health-fitness', 'Health & Fitness'), ('kids', 'Kids'), ('lifestyle', 'Lifestyle'), ('medical', 'Medical'), ('music-audio', 'Music & Audio'), ('navigation', 'Maps & Navigation'), ('news', 'News & Magazines'), ('photo-video', 'Photo & Video'), ('productivity', 'Productivity'), ('shopping', 'Shopping / E-commerce'), ('social', 'Social Networking'), ('sports', 'Sports'), ('tools', 'Tools & Utilities'), ('travel', 'Travel & Local'), ('weather', 'Weather'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
